@baseUrl = http://localhost:3000

###
@users = {{baseUrl}}/users
GET {{users}}

###
@userId = 48b06345-802c-4155-95f2-8c3594671805
GET {{users}}/{{userId}}

###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "pass"
}

###
@sessions = {{baseUrl}}/sessions
POST {{sessions}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "pass"
}