@baseUrl = http://localhost:3000

###
@users = {{baseUrl}}/users
GET {{users}}

###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "pass"
}

###
@sessions = {{baseUrl}}/sessions
POST {{sessions}}
Content-Type: application/json

{
  "name": "test",
  "password": "pass"
}