@baseUrl = http://localhost:3000

###
@users = {{baseUrl}}/users
GET {{users}}

###
@userId = 7dda668d-a29e-42f6-98ed-de8141ddf487
GET {{users}}/{{userId}}

###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}