@baseUrl = http://localhost:3000

###
@users = {{baseUrl}}/users
GET {{users}}

###
@userId = 
GET {{users}}/{{userId}}

###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}