@baseUrl = http://localhost:3000

###
@users = {{baseUrl}}/users
GET {{users}}

###
@userId = af3c813b-d394-4ff8-86cf-7618efbff6dc
GET {{users}}/{{userId}}

###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}