env:
  es2021: true
  node: true
plugins: ['prettier']
extends: ['eslint:recommended', 'prettier']
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 1 # Means warning
  prettier/prettier: 2 # Means error
