@protocol = {{$dotenv PROTOCOL}}
@host = {{$dotenv HOST}}
@port = {{$dotenv PORT}}
@apiVersion = {{$dotenv API_VERSION}}
@baseUrl = {{protocol}}://{{host}}:{{port}}/{{apiVersion}}
###
GET {{baseUrl}}
###
@users = {{baseUrl}}/users
GET {{users}}
###
@id = d1524249-59ad-4aea-b492-0dd1ff54e227
GET {{users}}/{{id}}
###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123"
}