@protocol = {{$dotenv PROTOCOL}}
@host = {{$dotenv HOST}}
@port = {{$dotenv PORT}}
@baseUrl = {{protocol}}://{{host}}:{{port}}
###
GET {{baseUrl}}
###
@users = {{baseUrl}}/users
GET {{users}}
###
@id = 18147d68-c4fe-4892-9cdc-6d4a16ecabe8
GET {{users}}/{{id}}
###
POST {{users}}
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123"
}